### ISSUE TITLE
Sound plugin stopped working after Datenstrom Yellow had been updated to version 0.9

### ISSUE THREAD

**Issue by v-bulynkin** [GiovanniSalmeri/yellow-sound#1]
Hello!

The sound plugin worked great on version 0.8 but after upgrade it stopped.
The [yellow-typography](https://github.com/GiovanniSalmeri/yellow-typography) also doesn't work.

I tried to reinstall but it didn't help.

These are working plugins and their version now on my installation:
```bash
user@web:~$ docker exec yellow-php php83 yellow.php about
Datenstrom Yellow 0.9
Blog 0.9.1
Copenhagen 0.9.1
Core 0.9.4
Draft 0.9.1
Edit 0.9.4
English 0.9.1
Feed 0.9.1
Gallery 0.9.2
Generate 0.9.3
German 0.9.1
Highlight 0.9.2
Image 0.9.2
Markdown 0.9.1
Previousnext 0.9.1
Search 0.9.1
Serve 0.9.1
Slider 0.9.2
Stockholm 0.9.1
Toc 0.9.1
Update 0.9.4
Youtube 0.9.1

```

**Comment by GiovanniSalmeri** [comment]
I will update my extensions to the new API as soon as possible (perhaps before midnight 🥲 ). Sorry for the delay! Anyway, I am happy to know that you find Sound extension useful!

**Comment by GiovanniSalmeri** [comment]
https://github.com/datenstrom/yellow/discussions/967#discussioncomment-9185201

In order to make Sound updatable with `yellow.php update all` I should submit it for review to the Yellow maintainers, but actually I consider it still a bit experimental. Above all, I was thinking about simplifying and reorganising the features of Sound and [Video](https://github.com/GiovanniSalmeri/yellow-video) this way:

* Sound: only audio files (local or remote)
* Video: only video files (local or remote), with optional captions
* Mediaplatform: only online video or audio platforms (Dailymotion, Vimeo, Soundcloud etc.)

Would it be convenient for you?

**Comment by v-bulynkin** [comment]
Yes, your plugin is great, thank you so much. Especially I appreciate playlists.
This division is perfectly convenient for me.

**Comment by GiovanniSalmeri** [comment]
@v-bulynkin Now updated. I made some quick tests and it seems to work as before. Could you check when you have some time? Thank you!

**Comment by v-bulynkin** [comment]
Thank you for the update, it works!
However, zip file haven't installed itself after I had copied it to the `\system\extensions` directory. The only thing was done is an added paragraph to `\system\extensions\yellow-extension.ini`.
I manually copied `sound*` files to `/system/workers` and also added options to `\system\extensions\yellow-system.ini`. After that, it started working.

**Comment by GiovanniSalmeri** [comment]
> However, zip file haven't installed itself after I had copied it to the \system\extensions directory.

🤔 It's strange, I have just tried once again with a fresh installation of Yellow 0.9 and the files have been correctly installed... Anyway I'm glad that the extension in itself works well!

**Comment by v-bulynkin** [comment]
Perhaps, there is something about file permissions on my side.
Anyway, the problem is solved! :)

![изображение](https://github.com/GiovanniSalmeri/yellow-sound/assets/56349712/1e95ab5e-63e8-4ab0-8769-b116443677ab)

Thanks a lot!
